services:
  - type: web
    name: neuralkb-api
    env: python
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENCODE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: multimodal-index
      - key: PINECONE_REGION
        value: us-east-1
    autoDeploy: true
